# Netlify CMS configuration integrating it with Jekyll.
# © 2018 Filip Zrůst
#
# This file is part of JAMstack Experiments.
#
# JAMstack Experiments is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public
# License as published by the Free Software Foundation, either
# version 3 of the License, or any later version.
#
# JAMstack Experiments is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with JAMstack Experiments. If not,
# see <http://www.gnu.org/licenses/>.

backend:
  name: git-gateway
  branch: jekyll

media_folder: assets/uploads

collections:
  - name: post
    label: Post
    folder: _posts
    sort: date:desc
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: layout
        label: Layout
        widget: hidden
        default: post
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
      - name: categories
        label: Categories
        widget: string
        required: false
    meta:
      - name: date
        label: Publish Date
        widget: datetime
        format: YYYY-MM-DD HH:mm:ss ZZ
